_BASE_: "../Base-RCNN-FPN.yaml" #  This refers to a base configuration file that serves as the foundation for the current configuration. It provides default values for various parameters, and the current configuration overrides or extends these values.
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl" # This specifies the weight file for the model. In this case, it points to an ImageNet pre-trained ResNet-101 model provided by Detectron2. Pre-trained weights are often used as an initialization for the model to leverage the learned features from a large-scale dataset.
  MASK_ON: False #  This indicates whether the model should include a mask prediction branch in addition to the bounding box prediction branch.
  RESNETS:
    DEPTH: 101 # This specifies the depth or size of the ResNet backbone network used in the model. In this case, a ResNet-101 backbone is employed.
  ROI_HEADS:
    NUM_CLASSES: 164 # This defines the number of object classes the model should predict. In this configuration, the model is trained to detect objects from 164 different classes.
DATASETS:
  # TRAIN: ('children_books_train_base',)
  # TEST: ('children_books_train_novel',)
  TRAIN: ('children_books_train_base',)
  TEST: ('children_books_test',)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (15000, ) # This defines the iteration steps at which the learning rate is adjusted during training. In this case, the learning rate is reduced at 85,000 and 100,000 iterations.
  MAX_ITER: 20000 # This specifies the maximum number of iterations for training the model. The training process will iterate through the dataset and update the model's parameters until this maximum number of iterations is reached.
  BASE_LR: 0.001
OUTPUT_DIR: "checkpoints/children_books/faster_rcnn/faster_rcnn_R_101_FPN_base_iter20000"
